### ISSUE TITLE
没有办法从转发的聊天记录里直接复制

### ISSUE THREAD

**Issue by xsdcxsdc** [LincZero/obsidian-chat-view-qq#9]
图片会丢失

**Comment by LincZero** [comment]
转发的聊天记录是可以复制的, 刚试过了.
我觉得你说的图片丢失不是因为是在聊天记录里复制, 而是因为qq有时会给图片起一些很奇怪的名字(包含非法字符). 直接拖拽qq图片到Ob或Typora也会有这种情况. 这个之前在另一个issue里提过 #3 

该bug未解决之前只能通过手动复制图片到Ob里并重命名和重新引用该图片解决
